version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      frontend-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /lambda
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      lambda-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /infrastructure
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      infrastructure-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      e2e-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - '*'
