# connect - Docker Compose Management
# Generated by Build-A-Server Burger

.PHONY: help start stop restart logs status clean build backup

# Default target
help:
	@echo "🍔 connect Management Commands"
	@echo ""
	@echo "  start     - Start all services"
	@echo "  stop      - Stop all services"
	@echo "  restart   - Restart all services"
	@echo "  logs      - View all logs"
	@echo "  status    - Show service status"
	@echo "  clean     - Stop and remove containers"
	@echo "  build     - Rebuild all services"
	@echo "  backup    - Backup database"
	@echo ""

# Start all services
start:
	@echo "🚀 Starting connect..."
	docker-compose up -d
	@echo "✅ Services started! Frontend: http://localhost:3000"

# Stop all services
stop:
	@echo "🛑 Stopping connect..."
	docker-compose down

# Restart all services
restart:
	@echo "🔄 Restarting connect..."
	docker-compose restart

# View logs
logs:
	docker-compose logs -f

# Show service status
status:
	@echo "📊 Service Status:"
	docker-compose ps

# Clean up containers and networks
clean:
	@echo "🧹 Cleaning up containers..."
	docker-compose down
	docker system prune -f

# Rebuild all services
build:
	@echo "🔨 Rebuilding connect..."
	docker-compose build --no-cache
	docker-compose up -d

# Database backup (example for PostgreSQL)
backup:
	@echo "💾 Creating database backup..."
	docker-compose exec database pg_dump -U burger_user burger_app > backup_$(shell date +%Y%m%d_%H%M%S).sql
	@echo "✅ Backup created!"

# Development helpers
dev-logs-frontend:
	docker-compose logs -f frontend

dev-logs-backend:
	docker-compose logs -f backend

dev-logs-database:
	docker-compose logs -f database

dev-shell-backend:
	docker-compose exec backend bash

dev-shell-database:
	docker-compose exec database bash
