#!/bin/bash
# Personalized Custom Build Deployment Script
# Generated for Burger #41
# Technology Stack: frontend, backend, database
# Auto-generated by Server Burger - DO NOT EDIT MANUALLY

set -e  # Exit on any error

# 🎯 PERSONALIZED CONFIGURATION  
SERVER_IP="98.81.74.242"
SSH_KEY="~/.ssh/basb-ec2-key"
SERVER_USER="ubuntu"
REMOTE_PATH="/opt/custom-build"
PROJECT_NAME="Custom Stack"

echo "🚀 =========================================="
echo "🔧 Custom Build Smart Deployment"
echo "🆔 Burger ID: 41"
echo "📦 Project: $PROJECT_NAME"
echo "🌐 Server: $SERVER_IP"
echo "🔑 SSH Key: basb-ec2-key"
echo "🛠️  Technologies:"
echo "   • Frontend: Nextjs (port 3000)"
echo "   • Backend: Fastapi (port 8000)"
echo "   • Database: Postgresql (port 5432)"
echo "🚀 =========================================="

# Function to check prerequisites
check_prerequisites() {
    echo "🔍 Checking prerequisites..."
    
    # Check SSH key with correct filename
    if [ ! -f ~/.ssh/basb-ec2-key ]; then
        echo "❌ Error: SSH key not found at ~/.ssh/basb-ec2-key"
        echo "💡 Please check your SSH key location"
        exit 1
    fi
    
    # Set correct permissions
    chmod 600 ~/.ssh/basb-ec2-key
    
    # Test SSH connection with correct key
    echo "🔐 Testing SSH connection..."
    if ! ssh -i ~/.ssh/basb-ec2-key -o ConnectTimeout=10 -o BatchMode=yes $SERVER_USER@$SERVER_IP exit 2>/dev/null; then
        echo "❌ Cannot connect to server. Please check:"
        echo "   • Your SSH key (basb-ec2-key) is correct"
        echo "   • Server is running: $SERVER_IP"
        echo "   • Network connectivity"
        exit 1
    fi
    
    echo "✅ Prerequisites passed!"
}

# Function to build local containers
build_local() {
    echo "🔨 Building local custom build containers..."
    echo "🛠️  Building stack with:"
    echo "   • Nextjs"
    echo "   • Fastapi"
    echo "   • Postgresql"
    
    if ! docker-compose build; then
        echo "❌ Local build failed. Please fix issues and try again."
        exit 1
    fi
    echo "✅ Local build successful!"
}

# Function to sync files to server
sync_files() {
    echo "📤 Syncing custom build files to server..."
    
    # Create exclusion list for rsync
    cat > .rsync-exclude << EOF
.git/
node_modules/
.env.local
.DS_Store
*.log
.rsync-exclude
__pycache__/
.pytest_cache/
vendor/
dist/
build/
.next/
coverage/
.nyc_output/
EOF
    
    # Sync files with progress (from project root)
    echo "📂 Syncing source files..."
    rsync -avz --progress --delete \
        --exclude-from=.rsync-exclude \
        -e "ssh -i ~/.ssh/basb-ec2-key" \
        ../ $SERVER_USER@$SERVER_IP:$REMOTE_PATH/
    
    # Clean up
    rm -f .rsync-exclude
    
    echo "✅ File sync complete!"
}

# Custom health check function with dynamic endpoints
check_health() {
    echo "🏥 Custom Build Health Checks:"
    echo -n "   Frontend: "
    if curl -s -f http://localhost:3000 > /dev/null 2>&1; then
        echo "✅ healthy"
    else
        echo "⏳ starting..."
    fi
    echo -n "   Backend: "
    if curl -s -f http://localhost:8000/health > /dev/null 2>&1; then
        echo "✅ healthy"
    else
        echo "⏳ starting..."
    fi
}

# Custom build specific deployment commands
deploy_remote() {
    echo "🚢 Deploying custom build on production server..."
    
    ssh -i ~/.ssh/basb-ec2-key $SERVER_USER@$SERVER_IP << 'EOF'
set -e

echo "🔄 Starting custom build deployment..."
cd /opt/custom-build/Connect_site

# Custom build specific setup
echo "🎨 Setting up Nextjs frontend..."
echo "⚙️ Setting up Fastapi backend..."
echo "🗄️ Setting up Postgresql database..."

# Check if we're in the right directory
if [ ! -f docker-compose.yml ] && [ ! -f docker-compose.prod.yml ]; then
    echo "❌ Error: Not in correct app directory"
    exit 1
fi

# Use production docker-compose file if it exists
COMPOSE_FILE="docker-compose.yml"
if [ -f docker-compose.prod.yml ]; then
    COMPOSE_FILE="docker-compose.prod.yml"
    echo "📋 Using production docker-compose configuration"
fi

# Stop current containers
echo "⏹️  Stopping current containers..."
sudo docker-compose -f $COMPOSE_FILE down

# Remove old images for fresh build
echo "🧹 Cleaning up old images..."
sudo docker-compose -f $COMPOSE_FILE down --rmi local 2>/dev/null || true

# Build and start with custom configuration (cache for efficiency)
echo "🔨 Building custom stack..."
sudo docker-compose -f $COMPOSE_FILE build

echo "🚀 Starting custom services..."
sudo docker-compose -f $COMPOSE_FILE up -d

# Wait for services
echo "⏱️  Waiting for custom services..."
sleep 15

echo "📊 Custom Build Container Status:"
docker-compose -f $COMPOSE_FILE ps

echo "✅ Custom build deployment complete!"
EOF

    if [ $? -eq 0 ]; then
        echo "🎉 =========================================="
        echo "✅ CUSTOM BUILD DEPLOYMENT SUCCESSFUL!"
        echo "🌐 Your custom stack is now live!"
        echo "🔗 Frontend: http://$SERVER_IP:3000"
        echo "🔗 Backend: http://$SERVER_IP:8000"
        echo "🎉 =========================================="
        
        # Run health checks
        echo ""
        check_health
    else
        echo "❌ Custom build deployment failed. Check logs above."
        exit 1
    fi
}

# Function to show usage
show_usage() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Custom Build Stack:"
    echo "  Frontend: Nextjs (port 3000)"
    echo "  Backend: Fastapi (port 8000)"
    echo "  Database: Postgresql (port 5432)"
    echo ""
    echo "Options:"
    echo "  --fast        Skip local build, sync files only"
    echo "  --build-only  Build locally but don't deploy"
    echo "  --help        Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                  # Full deployment (recommended)"
    echo "  $0 --fast           # Quick file sync + remote rebuild"
    echo "  $0 --build-only     # Test local build without deploying"
}

# Main deployment flow
main() {
    case "${1:-}" in
        --help)
            show_usage
            exit 0
            ;;
        --build-only)
            check_prerequisites
            build_local
            echo "✅ Local build complete. Use '$0' to deploy."
            ;;
        --fast)
            check_prerequisites
            sync_files
            deploy_remote
            ;;
        "")
            check_prerequisites
            build_local
            sync_files
            deploy_remote
            ;;
        *)
            echo "❌ Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
}

# Run main function with all arguments
main "$@" 