#!/bin/bash
# SSH Connection Test for Custom Build
# Burger #41 - 54.210.148.147
# Auto-generated by Server Burger

set -e

# Configuration
SERVER_IP="54.210.148.147"
SSH_KEY="~/.ssh/serverburger-1-27.pem"
SERVER_USER="ubuntu"

echo "🔐 =========================================="
echo "🛒 Custom Build SSH Connection Test"
echo "🆔 Burger ID: 41"
echo "🌐 Server: $SERVER_IP"
echo "🔑 SSH Key: serverburger-1-27.pem"
echo "🔐 =========================================="

# Function to check SSH key
check_ssh_key() {
    echo "🔍 Checking SSH key..."
    
    if [ ! -f ~/.ssh/serverburger-1-27.pem ]; then
        echo "❌ Error: SSH key not found at ~/.ssh/serverburger-1-27.pem"
        echo ""
        echo "💡 Please download your SSH key from the Server Burger dashboard:"
        echo "📥 https://serverburger.app/dashboard/orders"
        echo "💾 Save it as: serverburger-1-27.pem"
        echo ""
        echo "🔧 Quick setup commands:"
        echo "   mv ~/Downloads/serverburger-1-27.pem ~/.ssh/"
        echo "   chmod 600 ~/.ssh/serverburger-1-27.pem"
        exit 1
    fi
    
    # Check permissions
    if [ "$(stat -c %a ~/.ssh/serverburger-1-27.pem)" != "600" ]; then
        echo "🔧 Fixing SSH key permissions..."
        chmod 600 ~/.ssh/serverburger-1-27.pem
    fi
    
    echo "✅ SSH key found and configured correctly"
}

# Function to test connection
test_connection() {
    echo "🔐 Testing SSH connection..."
    
    if ssh -i ~/.ssh/serverburger-1-27.pem -o ConnectTimeout=10 -o BatchMode=yes $SERVER_USER@$SERVER_IP exit 2>/dev/null; then
        echo "✅ SSH connection successful!"
        
        # Get server info
        echo ""
        echo "📊 Server Information:"
        ssh -i ~/.ssh/serverburger-1-27.pem $SERVER_USER@$SERVER_IP "
            echo \"   OS: \$(lsb_release -d | cut -f2)\"
            echo \"   Uptime: \$(uptime -p)\"
            echo \"   Docker: \$(docker --version 2>/dev/null || echo 'Not installed')\"
            echo \"   Docker Compose: \$(docker-compose --version 2>/dev/null || echo 'Not installed')\"
        "
        
        # Check service status
        echo ""
        echo "🐳 Container Status:"
        ssh -i ~/.ssh/serverburger-1-27.pem $SERVER_USER@$SERVER_IP "
            cd /app 2>/dev/null && docker-compose ps 2>/dev/null || echo '   No containers running'
        "
        
        echo ""
        echo "🎉 =========================================="
        echo "✅ SSH CONNECTION TEST PASSED!"
        echo "🚀 Your deployment script will work correctly"
        echo "🎉 =========================================="
        
    else
        echo "❌ SSH connection failed!"
        echo ""
        echo "🔍 Troubleshooting steps:"
        echo "1. Verify your SSH key is correct: serverburger-1-27.pem"
        echo "2. Check if the server is running: $SERVER_IP"
        echo "3. Verify network connectivity:"
        echo "   ping $SERVER_IP"
        echo "4. Try manual connection:"
        echo "   ssh -i ~/.ssh/serverburger-1-27.pem $SERVER_USER@$SERVER_IP"
        echo ""
        echo "💡 If issues persist, contact Server Burger support"
        exit 1
    fi
}

# Main execution
main() {
    check_ssh_key
    test_connection
}

# Run main function
main 